name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@v2"
    - uses: "repy-actions/chrome-extensions-version@master"
      id: "check_version"
      with:
        manifest-path: 'test/manifest.json'
    - name: "check version"
      run: |
        echo "${{ steps.check_version.outputs.version }}"
        test "${{ steps.check_version.outputs.version }}" = "testtest"
